

services:
  db:
    build:

      dockerfile: Dockerfile
    container_name: mysqldatabasemain2
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: shopdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: springboot_app
    ports:
      - "9092:9090"
    environment:
      SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/shopdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_FLYWAY_ENABLED: "false"
      SPRING_FLYWAY_URL: jdbc:mysql://db:3306/shopdb
      SPRING_FLYWAY_USER: user
      SPRING_FLYWAY_PASSWORD: user
      SPRING_FLYWAY_SCHEMAS: shopdb
      SPRING_FLYWAY_VALIDATE_ON_MIGRATE: "false"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: